// ============================================================
//  DATA DUMMY — simula respuesta de API satelital LK
//  En producción, reemplazar generateFleet() con fetch() a la API real
// ============================================================

export const INITIAL_FLEET = [
  {
    id: 'PLK41485', alias: 'Unidad 01', bat: 12.60, vel: 89,
    evento: 'RPT', estado: 'ZGAR', curso: 'SE',
    lat: -41.02, lng: -65.98,
    ruta: 'Ruta Nacional 3, Río Negro, Sierra Grande, AR',
    destino: 'Comodoro Rivadavia', origen: 'Buenos Aires',
    etaHoras: 3.2, kmRecorridos: 1240, kmTotales: 1580,
    grupo: 'DTN',
  },
  {
    id: 'PLK41475', alias: 'Unidad 02', bat: 12.20, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'SO',
    lat: -38.95, lng: -68.07,
    ruta: 'Ruta Nacional 251, Río Negro, AR',
    destino: 'Neuquén', origen: 'Bahía Blanca',
    etaHoras: 1.1, kmRecorridos: 380, kmTotales: 430,
    grupo: 'DTN',
  },
  {
    id: 'PLK41457', alias: 'Unidad 03', bat: 12.00, vel: 29,
    evento: 'RPT', estado: 'ZGAR', curso: 'SO',
    lat: -38.72, lng: -62.27,
    ruta: 'Camino Parque Sesquicentenario, Bahía Blanca, AR',
    destino: 'Bahía Blanca', origen: 'Mar del Plata',
    etaHoras: 0.4, kmRecorridos: 395, kmTotales: 410,
    grupo: 'NPG',
  },
  {
    id: 'PLK41448', alias: 'Unidad 04', bat: 12.40, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'SO',
    lat: -40.10, lng: -65.00,
    ruta: 'Ruta Nacional 251, Barrio TGS, Depto. Conesa, Río Negro, AR',
    destino: 'Viedma', origen: 'Neuquén',
    etaHoras: 0.8, kmRecorridos: 290, kmTotales: 330,
    grupo: 'DTN',
  },
  {
    id: 'PLK41436', alias: 'Unidad 05', bat: 11.43, vel: 0,
    evento: 'CDS', estado: 'ZGAR', curso: 'SE',
    lat: -52.15, lng: -69.23,
    ruta: '257 CH, Magallanes y Antártica Chilena, San Gregorio, CL',
    destino: 'Punta Arenas', origen: 'Buenos Aires',
    etaHoras: null, kmRecorridos: 2890, kmTotales: 3100,
    grupo: 'CDS',
    sinSenal: true,
    minutesSinSenal: 47,
  },
  {
    id: 'PLK41406', alias: 'Unidad 06', bat: 12.60, vel: 7,
    evento: 'RPT', estado: 'ZGAR', curso: 'SO',
    lat: -40.55, lng: -65.10,
    ruta: 'Ruta Nacional 251, Depto. Conesa, Barrio TGS, AR',
    destino: 'Viedma', origen: 'Neuquén',
    etaHoras: 1.5, kmRecorridos: 265, kmTotales: 330,
    grupo: 'NPG',
  },
  {
    id: 'PLK41004', alias: 'Unidad 07', bat: 12.30, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'NO',
    lat: -43.25, lng: -65.30,
    ruta: 'Estacionamiento de camiones, Ruta Nacional 3, Rawson, Trelew, AR',
    destino: 'Comodoro Rivadavia', origen: 'Trelew',
    etaHoras: 2.8, kmRecorridos: 80, kmTotales: 390,
    grupo: 'DTN',
    detencionMin: 128,
  },
  {
    id: 'PLK41392', alias: 'Unidad 08', bat: 12.10, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'E',
    lat: -43.25, lng: -65.33,
    ruta: 'Ruta Nacional 3, Chubut, Trelew, AR',
    destino: 'Puerto Madryn', origen: 'Trelew',
    etaHoras: 0.6, kmRecorridos: 5, kmTotales: 68,
    grupo: 'DTN',
  },
  {
    id: 'PLK41376', alias: 'Unidad 09', bat: 12.20, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'NO',
    lat: -43.26, lng: -65.32,
    ruta: 'Estacionamiento, Ruta 3, La Laguna, U9100 Trelew, AR',
    destino: 'Comodoro Rivadavia', origen: 'Trelew',
    etaHoras: 3.1, kmRecorridos: 0, kmTotales: 370,
    grupo: 'DTN',
  },
  {
    id: 'PLK41368', alias: 'Unidad 10', bat: 10.70, vel: 0,
    evento: 'PTA+DTN', estado: 'ZGAR', curso: 'NO',
    lat: -34.63, lng: -58.36,
    ruta: 'Pinzón 1154, La Boca, 1167 Buenos Aires, AR',
    destino: 'Desconocido', origen: 'Buenos Aires',
    etaHoras: null, kmRecorridos: 0, kmTotales: 0,
    grupo: 'PTA+DTN',
    batCritica: true,
    diasSinMovimiento: 30,
  },
  {
    id: 'PLK40291', alias: 'Unidad 11', bat: 11.80, vel: 0,
    evento: 'DTN', estado: 'ZGAR', curso: 'O',
    lat: -40.73, lng: -65.00,
    ruta: 'San Antonio, Río Negro, Sierra Grande, AR',
    destino: 'Sierra Grande', origen: 'Viedma',
    etaHoras: 0.3, kmRecorridos: 160, kmTotales: 180,
    grupo: 'NPG',
  },
  {
    id: 'PLK40185', alias: 'Unidad 12', bat: 12.50, vel: 95,
    evento: 'RPT', estado: 'ZGAR', curso: 'N',
    lat: -37.20, lng: -61.00,
    ruta: 'Autopista Ruta 3, Buenos Aires, AR',
    destino: 'Buenos Aires', origen: 'Bahía Blanca',
    etaHoras: 2.1, kmRecorridos: 520, kmTotales: 700,
    grupo: 'NPG',
  },
];

// Alertas activas precargadas
export const INITIAL_ALERTS = [
  {
    id: 'A001', ts: new Date(Date.now() - 47 * 60000),
    tipo: 'sin_senal', nivel: 'critica',
    equipoId: 'PLK41436',
    titulo: 'Pérdida de señal GPS',
    desc: '47 min sin actualización de posición. Última ubicación: Magallanes, Chile.',
    resuelta: false,
  },
  {
    id: 'A002', ts: new Date(Date.now() - 3 * 3600000),
    tipo: 'bateria_critica', nivel: 'critica',
    equipoId: 'PLK41368',
    titulo: 'Batería crítica',
    desc: 'Batería en 10.70V — riesgo inminente de apagado del dispositivo.',
    resuelta: false,
  },
  {
    id: 'A003', ts: new Date(Date.now() - 3 * 3600000),
    tipo: 'inactividad', nivel: 'critica',
    equipoId: 'PLK41368',
    titulo: 'Inactividad prolongada (30 días)',
    desc: 'Sin movimiento desde Buenos Aires hace 30 días. Verificar estado físico del precinto.',
    resuelta: false,
  },
  {
    id: 'A004', ts: new Date(Date.now() - 128 * 60000),
    tipo: 'detencion', nivel: 'advertencia',
    equipoId: 'PLK41004',
    titulo: 'Detención no autorizada',
    desc: 'Detenido 2h 8min en Trelew — fuera de ventana habitual (< 90 min en este punto).',
    resuelta: false,
  },
  {
    id: 'A005', ts: new Date(Date.now() - 5 * 3600000),
    tipo: 'bateria_baja', nivel: 'advertencia',
    equipoId: 'PLK40291',
    titulo: 'Batería baja',
    desc: 'Batería en 11.80V — por debajo del umbral configurado de 12.0V.',
    resuelta: true,
  },
  {
    id: 'A006', ts: new Date(Date.now() - 6 * 3600000),
    tipo: 'velocidad', nivel: 'advertencia',
    equipoId: 'PLK41457',
    titulo: 'Velocidad atípica detectada',
    desc: 'Velocidad 29 km/h en tramo donde el perfil histórico indica > 80 km/h.',
    resuelta: true,
  },
  {
    id: 'A007', ts: new Date(Date.now() - 7 * 3600000),
    tipo: 'apertura', nivel: 'advertencia',
    equipoId: 'PLK41392',
    titulo: 'Evento CDS detectado',
    desc: 'Señal de apertura de precinto en control de ruta. Verificado por transportista.',
    resuelta: true,
  },
];

// Scores e insights IA por unidad
export const AI_INSIGHTS = {
  PLK41485: { score: 22, color: 'ok',  factors: ['Velocidad dentro del perfil', 'Ruta esperada activa', 'Batería en rango normal'], rec: 'Sin acción requerida.' },
  PLK41475: { score: 18, color: 'ok',  factors: ['Parada en punto habitual', 'Sin anomalías de trayecto', 'Batería OK'], rec: 'Sin acción requerida.' },
  PLK41457: { score: 31, color: 'med', factors: ['Velocidad por debajo del perfil histórico', 'Ruta activa', 'Cercanía al destino'], rec: 'Monitorear próxima hora.' },
  PLK41448: { score: 15, color: 'ok',  factors: ['Parada programada', 'Historial limpio', 'Batería OK'], rec: 'Sin acción requerida.' },
  PLK41436: { score: 78, color: 'hi',  factors: ['Sin señal GPS 47 min', 'Zona fronteriza de baja cobertura', 'Batería en descenso'], rec: 'Contactar transportista. Activar protocolo zona sin cobertura.' },
  PLK41406: { score: 24, color: 'ok',  factors: ['Circulación normal', 'Zona de ruta conocida', 'Batería OK'], rec: 'Sin acción requerida.' },
  PLK41004: { score: 41, color: 'med', factors: ['Detención 2h+ en Trelew', 'Zona habitual pero excede tiempo típico', 'Batería OK'], rec: 'Monitorear. Alertar si supera 3h.' },
  PLK41392: { score: 19, color: 'ok',  factors: ['Parada breve reciente', 'Evento CDS verificado', 'Sin anomalías'], rec: 'Sin acción requerida.' },
  PLK41376: { score: 20, color: 'ok',  factors: ['Parada habitual pre-partida', 'Ruta sin iniciar', 'Batería OK'], rec: 'Sin acción requerida.' },
  PLK41368: { score: 85, color: 'hi',  factors: ['Batería crítica (10.7V)', 'Sin movimiento 30 días', 'Riesgo de apagado inminente', 'Viaje sin completar'], rec: 'Verificar ubicación física. Enviar técnico. Urgente.' },
  PLK40291: { score: 35, color: 'med', factors: ['Batería por debajo del umbral', 'Velocidad promedio baja últimas 24h', 'Detenido en destino parcial'], rec: 'Revisar cargador del vehículo.' },
  PLK40185: { score: 14, color: 'ok',  factors: ['Velocidad dentro del perfil', 'Ruta activa sin desvíos', 'Batería OK'], rec: 'Sin acción requerida.' },
};

export const RISK_ZONES = [
  { zona: 'Ruta 3, Km 1400–1450 (Santa Cruz)', nivel: 'hi', incidencias: 8, desc: 'Zona de poca cobertura celular y GPS' },
  { zona: 'Frontera Argentina–Chile (Magallanes)', nivel: 'hi', incidencias: 6, desc: 'Pérdida frecuente de señal GPS' },
  { zona: 'Acceso sur CABA (La Boca)', nivel: 'med', incidencias: 4, desc: 'Historial de robos y manipulaciones' },
  { zona: 'Trelew – Estac. Ruta 3', nivel: 'med', incidencias: 3, desc: 'Detenciones prolongadas recurrentes' },
  { zona: 'Ruta 251, Depto. Conesa (Río Negro)', nivel: 'low', incidencias: 1, desc: 'Tramo monitoreable, historial limpio' },
];

export const CONFIG_DEFAULTS = {
  bat_critica_v: 11.5,
  bat_baja_v: 12.0,
  detencion_min: 90,
  vel_max_kmh: 130,
  gps_perdida_min: 20,
  ai_riesgo_alto: 65,
  notif_whatsapp: '',
  notif_email: '',
  notif_sms: '',
};
